CREATE DATABASE Senai_Patrimonios

USE Senai_Patrimonios

CREATE TABLE Sala
(
	IdSala				INT PRIMARY KEY IDENTITY
	,Nome				VARCHAR (200) NOT NULL
	,Andar				INT NOT NULL
	,Metragem			DECIMAL NOT NULL
);

CREATE TABLE Equipamento
(
	IdEquipamento			INT PRIMARY KEY IDENTITY
	,IdSala					INT FOREIGN KEY REFERENCES Sala (IdSala)
	,Marca					VARCHAR (200) NOT NULL
	,Tipo					VARCHAR (200) NOT NULL
	,Serie					DECIMAL NOT NULL
	,Descricao				VARCHAR (100) NOT NULL
	,Patrimonio				DECIMAL NOT NULL
	,Estado					VARCHAR (100) NOT NULL
);

CREATE TABLE Usuario
(
	IdUsuario				INT PRIMARY KEY IDENTITY
	,Email					VARCHAR (200) NOT NULL
	,Senha					VARCHAR (200) NOT NULL
);